using Raylib_cs;
using static Raylib_cs.Raylib;
using static UnirayEngine.UnirayEngine;
using Newtonsoft.Json;
using UnirayEngine;

namespace Program
{
    public class Program
    {
        public static void Main(string[] args)
        {
            // Be aware that the following code was generated by Uniray and might not be working anymore if modified
            InitWindow(1800, 900, "MyAwesomeProgram");
            SetWindowState(ConfigFlags.ResizableWindow);
            SetWindowState(ConfigFlags.MaximizedWindow);
            InitEngine();

            SetTargetFPS(60);
            while (!WindowShouldClose())
            {
                BeginDrawing();
                ClearBackground(Color.White);
                BeginMode3D(((UCamera)GetCurrentScene().GameObjects[0]).Camera);

                DrawScene();

                EndMode3D();
                EndDrawing();
            }
            CloseWindow();
        }
    }
}